site_name: sycl_points
site_author: fateshelled
repo_url: https://github.com/fateshelled/sycl_points
site_url: https://fateshelled.github.io/sycl_points/
site_description: "A C++ header-only point cloud processing library accelerated with SYCL."
theme:
  name: material
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/fateshelled/sycl_points
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - 設計思想: design_philosophy.md
